# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kviewer.ui'
#
# Created: Sun Jul 22 14:52:18 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.checkBox_ma = QtGui.QCheckBox(self.groupBox)
        self.checkBox_ma.setGeometry(QtCore.QRect(40, 10, 71, 16))
        self.checkBox_ma.setObjectName("checkBox_ma")
        self.checkBox_dmi = QtGui.QCheckBox(self.groupBox)
        self.checkBox_dmi.setGeometry(QtCore.QRect(40, 30, 71, 16))
        self.checkBox_dmi.setObjectName("checkBox_dmi")
        self.checkBox_macd = QtGui.QCheckBox(self.groupBox)
        self.checkBox_macd.setGeometry(QtCore.QRect(140, 10, 71, 16))
        self.checkBox_macd.setObjectName("checkBox_macd")
        self.checkBox_kdj = QtGui.QCheckBox(self.groupBox)
        self.checkBox_kdj.setGeometry(QtCore.QRect(250, 10, 71, 16))
        self.checkBox_kdj.setObjectName("checkBox_kdj")
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(140, 30, 71, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(250, 30, 71, 16))
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 2, 1)
        self.pushButton_draw = QtGui.QPushButton(self.centralwidget)
        self.pushButton_draw.setObjectName("pushButton_draw")
        self.gridLayout.addWidget(self.pushButton_draw, 1, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_plot = QtGui.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_plot)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_plot_field = QtGui.QHBoxLayout()
        self.horizontalLayout_plot_field.setObjectName("horizontalLayout_plot_field")
        self.label_para = QtGui.QLabel(self.tab_plot)
        self.label_para.setFrameShape(QtGui.QFrame.Box)
        self.label_para.setObjectName("label_para")
        self.horizontalLayout_plot_field.addWidget(self.label_para)
        self.label_point = QtGui.QLabel(self.tab_plot)
        self.label_point.setFrameShape(QtGui.QFrame.Box)
        self.label_point.setObjectName("label_point")
        self.horizontalLayout_plot_field.addWidget(self.label_point)
        self.label_file = QtGui.QLabel(self.tab_plot)
        self.label_file.setFrameShape(QtGui.QFrame.Box)
        self.label_file.setObjectName("label_file")
        self.horizontalLayout_plot_field.addWidget(self.label_file)
        self.verticalLayout.addLayout(self.horizontalLayout_plot_field)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_plot, "")
        self.tab_para = QtGui.QWidget()
        self.tab_para.setObjectName("tab_para")
        self.groupBox_3 = QtGui.QGroupBox(self.tab_para)
        self.groupBox_3.setGeometry(QtCore.QRect(400, 110, 361, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(30, 40, 41, 16))
        self.label.setObjectName("label")
        self.lineEdit_macd_short = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_macd_short.setGeometry(QtCore.QRect(80, 40, 41, 20))
        self.lineEdit_macd_short.setObjectName("lineEdit_macd_short")
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(150, 40, 31, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_macd_long = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_macd_long.setGeometry(QtCore.QRect(190, 40, 41, 20))
        self.lineEdit_macd_long.setObjectName("lineEdit_macd_long")
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(260, 40, 21, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_macd_m = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_macd_m.setGeometry(QtCore.QRect(280, 40, 41, 20))
        self.lineEdit_macd_m.setObjectName("lineEdit_macd_m")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_para)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 110, 371, 90))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 4, 1, 1)
        self.lineEdit_ma_n3 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ma_n3.setObjectName("lineEdit_ma_n3")
        self.gridLayout_2.addWidget(self.lineEdit_ma_n3, 0, 5, 1, 1)
        self.lineEdit_ma_n2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ma_n2.setObjectName("lineEdit_ma_n2")
        self.gridLayout_2.addWidget(self.lineEdit_ma_n2, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.lineEdit_ma_n1 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ma_n1.setObjectName("lineEdit_ma_n1")
        self.gridLayout_2.addWidget(self.lineEdit_ma_n1, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_ma_n4 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ma_n4.setObjectName("lineEdit_ma_n4")
        self.gridLayout_2.addWidget(self.lineEdit_ma_n4, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 2, 1, 1)
        self.lineEdit_ma_n5 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ma_n5.setObjectName("lineEdit_ma_n5")
        self.gridLayout_2.addWidget(self.lineEdit_ma_n5, 1, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 4, 1, 1)
        self.comboBox_ma = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_ma.setObjectName("comboBox_ma")
        self.comboBox_ma.addItem("")
        self.comboBox_ma.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_ma, 1, 5, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_para)
        self.groupBox_5.setGeometry(QtCore.QRect(400, 10, 361, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_opr_file = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_opr_file.setGeometry(QtCore.QRect(30, 40, 75, 23))
        self.pushButton_opr_file.setObjectName("pushButton_opr_file")
        self.label_opr = QtGui.QLabel(self.groupBox_5)
        self.label_opr.setGeometry(QtCore.QRect(130, 40, 54, 12))
        self.label_opr.setObjectName("label_opr")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_para)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 371, 90))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 351, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_contract = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_contract.setObjectName("lineEdit_contract")
        self.gridLayout_3.addWidget(self.lineEdit_contract, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.comboBox_bar = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_bar.setObjectName("comboBox_bar")
        self.comboBox_bar.addItem("")
        self.comboBox_bar.addItem("")
        self.comboBox_bar.addItem("")
        self.comboBox_bar.addItem("")
        self.comboBox_bar.addItem("")
        self.comboBox_bar.addItem("")
        self.comboBox_bar.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_bar, 0, 4, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 3, 1, 1)
        self.dateEdit_end = QtGui.QDateEdit(self.gridLayoutWidget_2)
        self.dateEdit_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 6, 30), QtCore.QTime(0, 0, 0)))
        self.dateEdit_end.setObjectName("dateEdit_end")
        self.gridLayout_3.addWidget(self.dateEdit_end, 1, 4, 1, 1)
        self.dateEdit_start = QtGui.QDateEdit(self.gridLayoutWidget_2)
        self.dateEdit_start.setObjectName("dateEdit_start")
        self.gridLayout_3.addWidget(self.dateEdit_start, 1, 2, 1, 1)
        self.pushButton_set_para = QtGui.QPushButton(self.tab_para)
        self.pushButton_set_para.setGeometry(QtCore.QRect(360, 330, 75, 23))
        self.pushButton_set_para.setObjectName("pushButton_set_para")
        self.groupBox_6 = QtGui.QGroupBox(self.tab_para)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 210, 371, 80))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_kdj_n = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_kdj_n.setGeometry(QtCore.QRect(40, 30, 51, 20))
        self.lineEdit_kdj_n.setObjectName("lineEdit_kdj_n")
        self.lineEdit_kdj_m1 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_kdj_m1.setGeometry(QtCore.QRect(160, 30, 51, 20))
        self.lineEdit_kdj_m1.setObjectName("lineEdit_kdj_m1")
        self.lineEdit_kdj_m2 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_kdj_m2.setGeometry(QtCore.QRect(270, 30, 51, 20))
        self.lineEdit_kdj_m2.setObjectName("lineEdit_kdj_m2")
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 21, 16))
        self.label_11.setObjectName("label_11")
        self.label_15 = QtGui.QLabel(self.groupBox_6)
        self.label_15.setGeometry(QtCore.QRect(140, 30, 21, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.groupBox_6)
        self.label_16.setGeometry(QtCore.QRect(250, 30, 21, 16))
        self.label_16.setObjectName("label_16")
        self.groupBox_7 = QtGui.QGroupBox(self.tab_para)
        self.groupBox_7.setGeometry(QtCore.QRect(400, 210, 361, 81))
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit_dmi_n = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_dmi_n.setGeometry(QtCore.QRect(70, 30, 41, 20))
        self.lineEdit_dmi_n.setObjectName("lineEdit_dmi_n")
        self.lineEdit_dmi_m = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_dmi_m.setGeometry(QtCore.QRect(190, 30, 41, 20))
        self.lineEdit_dmi_m.setObjectName("lineEdit_dmi_m")
        self.label_17 = QtGui.QLabel(self.groupBox_7)
        self.label_17.setGeometry(QtCore.QRect(40, 30, 31, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.groupBox_7)
        self.label_18.setGeometry(QtCore.QRect(170, 30, 21, 16))
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.tab_para, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "指标开关", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ma.setText(QtGui.QApplication.translate("MainWindow", "MA", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_dmi.setText(QtGui.QApplication.translate("MainWindow", "DMI", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_macd.setText(QtGui.QApplication.translate("MainWindow", "MACD", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_kdj.setText(QtGui.QApplication.translate("MainWindow", "KDJ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("MainWindow", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("MainWindow", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_draw.setText(QtGui.QApplication.translate("MainWindow", "绘图", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "设置参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_para.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_point.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_file.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plot), QtGui.QApplication.translate("MainWindow", "行情", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "MACD参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Short", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_macd_short.setText(QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Long", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_macd_long.setText(QtGui.QApplication.translate("MainWindow", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_macd_m.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "MA参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "N1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "N3", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ma_n3.setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ma_n2.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "N2", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ma_n1.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "N4", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ma_n4.setText(QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "N5", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ma_n5.setText(QtGui.QApplication.translate("MainWindow", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "算法", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ma.setItemText(0, QtGui.QApplication.translate("MainWindow", "MA", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ma.setItemText(1, QtGui.QApplication.translate("MainWindow", "EMA", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "回测文件", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_opr_file.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_opr.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "公共参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "周期", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "合约", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_bar.setItemText(0, QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_bar.setItemText(1, QtGui.QApplication.translate("MainWindow", "60", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_bar.setItemText(2, QtGui.QApplication.translate("MainWindow", "300", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_bar.setItemText(3, QtGui.QApplication.translate("MainWindow", "600", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_bar.setItemText(4, QtGui.QApplication.translate("MainWindow", "900", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_bar.setItemText(5, QtGui.QApplication.translate("MainWindow", "1800", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_bar.setItemText(6, QtGui.QApplication.translate("MainWindow", "3600", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "开始时间", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "结束时间", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_set_para.setText(QtGui.QApplication.translate("MainWindow", "设置", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "KDJ参数", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_kdj_n.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_kdj_m1.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_kdj_m2.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "M1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "M2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "DMI参数", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_dmi_n.setText(QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_dmi_m.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_para), QtGui.QApplication.translate("MainWindow", "参数设置", None, QtGui.QApplication.UnicodeUTF8))

