# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(398, 494)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 351, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 3, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.gridLayoutWidget_2)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_2.addWidget(self.dateEdit_2, 1, 4, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget_2)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(110, 30, 54, 12))
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.lineEdit_ma_n3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ma_n3.setObjectName("lineEdit_ma_n3")
        self.gridLayout.addWidget(self.lineEdit_ma_n3, 0, 5, 1, 1)
        self.lineEdit_ma_n2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ma_n2.setObjectName("lineEdit_ma_n2")
        self.gridLayout.addWidget(self.lineEdit_ma_n2, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.lineEdit_ma_n1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ma_n1.setObjectName("lineEdit_ma_n1")
        self.gridLayout.addWidget(self.lineEdit_ma_n1, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_ma_n4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ma_n4.setObjectName("lineEdit_ma_n4")
        self.gridLayout.addWidget(self.lineEdit_ma_n4, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
        self.lineEdit_ma_n5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ma_n5.setObjectName("lineEdit_ma_n5")
        self.gridLayout.addWidget(self.lineEdit_ma_n5, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 4, 1, 1)
        self.comboBox_ma = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_ma.setObjectName("comboBox_ma")
        self.comboBox_ma.addItem("")
        self.comboBox_ma.addItem("")
        self.gridLayout.addWidget(self.comboBox_ma, 1, 5, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form"))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Form", "公共参数"))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "周期"))
        self.label.setText(QtWidgets.QApplication.translate("Form", "合约"))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "0"))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "60"))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "300"))
        self.comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "600"))
        self.comboBox.setItemText(4, QtWidgets.QApplication.translate("Form", "900"))
        self.comboBox.setItemText(5, QtWidgets.QApplication.translate("Form", "1800"))
        self.comboBox.setItemText(6, QtWidgets.QApplication.translate("Form", "3600"))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "开始时间"))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "结束时间"))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("Form", "回测文件"))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("Form", "PushButton"))
        self.label_11.setText(QtWidgets.QApplication.translate("Form", "TextLabel"))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Form", "MA参数"))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "N1"))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "N3"))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "N2"))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "N4"))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "N5"))
        self.label_10.setText(QtWidgets.QApplication.translate("Form", "算法"))
        self.comboBox_ma.setItemText(0, QtWidgets.QApplication.translate("Form", "MA"))
        self.comboBox_ma.setItemText(1, QtWidgets.QApplication.translate("Form", "EMA"))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("Form", "MACD参数"))
        self.pushButton.setText(QtWidgets.QApplication.translate("Form", "确定"))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("Form", "取消"))

